# .pre-commit-hooks.yaml
-   id: check-python-version-consistency
    name: Check Python version consistency (pyproject.toml)
    description: Checks whether 'requires-python' is consistent with 'classifiers'.
    entry: check_python_versions.py  # Path to a script in this repository
    language: python
    additional_dependencies: [
        "packaging>=20.0",
        "tomli>=1.0.0; python_version < '3.11'" # Tomli only for Py < 3.11
    ]
    files: ^pyproject\.toml$
    pass_filenames: false
